version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    network_mode: "host"
    volumes:
      - .:/app
      - /app/node_modules
    restart: on-failure

